[server]
address = "127.0.0.1"
maxUploadSize = 100
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#116D65"
backgroundColor = "#F6F7F4"
secondaryBackgroundColor = "#EBF0EB"
textColor = "#18272E"
font = "sans serif"

[client]
toolbarMode = "minimal"
